// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ota_service.proto

#include "ota_service.pb.h"

#include <algorithm>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
#include "google/protobuf/generated_message_tctable_impl.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace ota {

inline constexpr StatusResponse::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : message_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        status_{static_cast< ::ota::StatusResponse_Status >(0)},
        progress_{0},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR StatusResponse::StatusResponse(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct StatusResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR StatusResponseDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~StatusResponseDefaultTypeInternal() {}
  union {
    StatusResponse _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 StatusResponseDefaultTypeInternal _StatusResponse_default_instance_;

inline constexpr StatusRequest::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : installation_id_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        device_id_{0},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR StatusRequest::StatusRequest(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct StatusRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR StatusRequestDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~StatusRequestDefaultTypeInternal() {}
  union {
    StatusRequest _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 StatusRequestDefaultTypeInternal _StatusRequest_default_instance_;

inline constexpr InstallResponse::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : message_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        installation_id_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        success_{false},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR InstallResponse::InstallResponse(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct InstallResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR InstallResponseDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~InstallResponseDefaultTypeInternal() {}
  union {
    InstallResponse _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 InstallResponseDefaultTypeInternal _InstallResponse_default_instance_;

inline constexpr InstallRequest::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : update_id_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        device_id_{0},
        allow_rollback_{false},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR InstallRequest::InstallRequest(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct InstallRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR InstallRequestDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~InstallRequestDefaultTypeInternal() {}
  union {
    InstallRequest _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 InstallRequestDefaultTypeInternal _InstallRequest_default_instance_;

inline constexpr DownloadRequest::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : update_id_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        jwt_token_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        device_id_{0},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR DownloadRequest::DownloadRequest(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct DownloadRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR DownloadRequestDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~DownloadRequestDefaultTypeInternal() {}
  union {
    DownloadRequest _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 DownloadRequestDefaultTypeInternal _DownloadRequest_default_instance_;

inline constexpr DownloadChunk::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : data_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        chunk_id_{0},
        last_chunk_{false},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR DownloadChunk::DownloadChunk(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct DownloadChunkDefaultTypeInternal {
  PROTOBUF_CONSTEXPR DownloadChunkDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~DownloadChunkDefaultTypeInternal() {}
  union {
    DownloadChunk _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 DownloadChunkDefaultTypeInternal _DownloadChunk_default_instance_;

inline constexpr CheckUpdateResponse::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : new_version_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        update_id_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        changelog_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        update_size_{::int64_t{0}},
        update_available_{false},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR CheckUpdateResponse::CheckUpdateResponse(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct CheckUpdateResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR CheckUpdateResponseDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~CheckUpdateResponseDefaultTypeInternal() {}
  union {
    CheckUpdateResponse _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 CheckUpdateResponseDefaultTypeInternal _CheckUpdateResponse_default_instance_;

inline constexpr CheckUpdateRequest::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : current_version_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        hardware_type_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        device_id_{0},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR CheckUpdateRequest::CheckUpdateRequest(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct CheckUpdateRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR CheckUpdateRequestDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~CheckUpdateRequestDefaultTypeInternal() {}
  union {
    CheckUpdateRequest _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 CheckUpdateRequestDefaultTypeInternal _CheckUpdateRequest_default_instance_;
}  // namespace ota
static ::_pb::Metadata file_level_metadata_ota_5fservice_2eproto[8];
static const ::_pb::EnumDescriptor* file_level_enum_descriptors_ota_5fservice_2eproto[1];
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_ota_5fservice_2eproto = nullptr;
const ::uint32_t TableStruct_ota_5fservice_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(
    protodesc_cold) = {
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::ota::CheckUpdateRequest, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::ota::CheckUpdateRequest, _impl_.device_id_),
    PROTOBUF_FIELD_OFFSET(::ota::CheckUpdateRequest, _impl_.current_version_),
    PROTOBUF_FIELD_OFFSET(::ota::CheckUpdateRequest, _impl_.hardware_type_),
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::ota::CheckUpdateResponse, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::ota::CheckUpdateResponse, _impl_.update_available_),
    PROTOBUF_FIELD_OFFSET(::ota::CheckUpdateResponse, _impl_.new_version_),
    PROTOBUF_FIELD_OFFSET(::ota::CheckUpdateResponse, _impl_.update_size_),
    PROTOBUF_FIELD_OFFSET(::ota::CheckUpdateResponse, _impl_.update_id_),
    PROTOBUF_FIELD_OFFSET(::ota::CheckUpdateResponse, _impl_.changelog_),
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::ota::DownloadRequest, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::ota::DownloadRequest, _impl_.device_id_),
    PROTOBUF_FIELD_OFFSET(::ota::DownloadRequest, _impl_.update_id_),
    PROTOBUF_FIELD_OFFSET(::ota::DownloadRequest, _impl_.jwt_token_),
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::ota::DownloadChunk, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::ota::DownloadChunk, _impl_.data_),
    PROTOBUF_FIELD_OFFSET(::ota::DownloadChunk, _impl_.chunk_id_),
    PROTOBUF_FIELD_OFFSET(::ota::DownloadChunk, _impl_.last_chunk_),
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::ota::InstallRequest, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::ota::InstallRequest, _impl_.device_id_),
    PROTOBUF_FIELD_OFFSET(::ota::InstallRequest, _impl_.update_id_),
    PROTOBUF_FIELD_OFFSET(::ota::InstallRequest, _impl_.allow_rollback_),
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::ota::InstallResponse, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::ota::InstallResponse, _impl_.success_),
    PROTOBUF_FIELD_OFFSET(::ota::InstallResponse, _impl_.message_),
    PROTOBUF_FIELD_OFFSET(::ota::InstallResponse, _impl_.installation_id_),
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::ota::StatusRequest, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::ota::StatusRequest, _impl_.device_id_),
    PROTOBUF_FIELD_OFFSET(::ota::StatusRequest, _impl_.installation_id_),
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::ota::StatusResponse, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::ota::StatusResponse, _impl_.status_),
    PROTOBUF_FIELD_OFFSET(::ota::StatusResponse, _impl_.progress_),
    PROTOBUF_FIELD_OFFSET(::ota::StatusResponse, _impl_.message_),
};

static const ::_pbi::MigrationSchema
    schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
        {0, -1, -1, sizeof(::ota::CheckUpdateRequest)},
        {11, -1, -1, sizeof(::ota::CheckUpdateResponse)},
        {24, -1, -1, sizeof(::ota::DownloadRequest)},
        {35, -1, -1, sizeof(::ota::DownloadChunk)},
        {46, -1, -1, sizeof(::ota::InstallRequest)},
        {57, -1, -1, sizeof(::ota::InstallResponse)},
        {68, -1, -1, sizeof(::ota::StatusRequest)},
        {78, -1, -1, sizeof(::ota::StatusResponse)},
};

static const ::_pb::Message* const file_default_instances[] = {
    &::ota::_CheckUpdateRequest_default_instance_._instance,
    &::ota::_CheckUpdateResponse_default_instance_._instance,
    &::ota::_DownloadRequest_default_instance_._instance,
    &::ota::_DownloadChunk_default_instance_._instance,
    &::ota::_InstallRequest_default_instance_._instance,
    &::ota::_InstallResponse_default_instance_._instance,
    &::ota::_StatusRequest_default_instance_._instance,
    &::ota::_StatusResponse_default_instance_._instance,
};
const char descriptor_table_protodef_ota_5fservice_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
    "\n\021ota_service.proto\022\003ota\"W\n\022CheckUpdateR"
    "equest\022\021\n\tdevice_id\030\001 \001(\005\022\027\n\017current_ver"
    "sion\030\002 \001(\t\022\025\n\rhardware_type\030\003 \001(\t\"\177\n\023Che"
    "ckUpdateResponse\022\030\n\020update_available\030\001 \001"
    "(\010\022\023\n\013new_version\030\002 \001(\t\022\023\n\013update_size\030\003"
    " \001(\003\022\021\n\tupdate_id\030\004 \001(\t\022\021\n\tchangelog\030\005 \001"
    "(\t\"J\n\017DownloadRequest\022\021\n\tdevice_id\030\001 \001(\005"
    "\022\021\n\tupdate_id\030\002 \001(\t\022\021\n\tjwt_token\030\003 \001(\t\"C"
    "\n\rDownloadChunk\022\014\n\004data\030\001 \001(\014\022\020\n\010chunk_i"
    "d\030\002 \001(\005\022\022\n\nlast_chunk\030\003 \001(\010\"N\n\016InstallRe"
    "quest\022\021\n\tdevice_id\030\001 \001(\005\022\021\n\tupdate_id\030\002 "
    "\001(\t\022\026\n\016allow_rollback\030\003 \001(\010\"L\n\017InstallRe"
    "sponse\022\017\n\007success\030\001 \001(\010\022\017\n\007message\030\002 \001(\t"
    "\022\027\n\017installation_id\030\003 \001(\t\";\n\rStatusReque"
    "st\022\021\n\tdevice_id\030\001 \001(\005\022\027\n\017installation_id"
    "\030\002 \001(\t\"\342\001\n\016StatusResponse\022*\n\006status\030\001 \001("
    "\0162\032.ota.StatusResponse.Status\022\020\n\010progres"
    "s\030\002 \001(\005\022\017\n\007message\030\003 \001(\t\"\200\001\n\006Status\022\013\n\007U"
    "NKNOWN\020\000\022\017\n\013DOWNLOADING\020\001\022\r\n\tVERIFYING\020\002"
    "\022\016\n\nINSTALLING\020\003\022\r\n\tREBOOTING\020\004\022\r\n\tCOMPL"
    "ETED\020\005\022\n\n\006FAILED\020\006\022\017\n\013ROLLED_BACK\020\0072\207\002\n\n"
    "OTAService\022C\n\016CheckForUpdate\022\027.ota.Check"
    "UpdateRequest\032\030.ota.CheckUpdateResponse\022"
    "<\n\016DownloadUpdate\022\024.ota.DownloadRequest\032"
    "\022.ota.DownloadChunk0\001\022:\n\rInstallUpdate\022\023"
    ".ota.InstallRequest\032\024.ota.InstallRespons"
    "e\022:\n\017GetUpdateStatus\022\022.ota.StatusRequest"
    "\032\023.ota.StatusResponseb\006proto3"
};
static ::absl::once_flag descriptor_table_ota_5fservice_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_ota_5fservice_2eproto = {
    false,
    false,
    1109,
    descriptor_table_protodef_ota_5fservice_2eproto,
    "ota_service.proto",
    &descriptor_table_ota_5fservice_2eproto_once,
    nullptr,
    0,
    8,
    schemas,
    file_default_instances,
    TableStruct_ota_5fservice_2eproto::offsets,
    file_level_metadata_ota_5fservice_2eproto,
    file_level_enum_descriptors_ota_5fservice_2eproto,
    file_level_service_descriptors_ota_5fservice_2eproto,
};

// This function exists to be marked as weak.
// It can significantly speed up compilation by breaking up LLVM's SCC
// in the .pb.cc translation units. Large translation units see a
// reduction of more than 35% of walltime for optimized builds. Without
// the weak attribute all the messages in the file, including all the
// vtables and everything they use become part of the same SCC through
// a cycle like:
// GetMetadata -> descriptor table -> default instances ->
//   vtables -> GetMetadata
// By adding a weak function here we break the connection from the
// individual vtables back into the descriptor table.
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_ota_5fservice_2eproto_getter() {
  return &descriptor_table_ota_5fservice_2eproto;
}
// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2
static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_ota_5fservice_2eproto(&descriptor_table_ota_5fservice_2eproto);
namespace ota {
const ::google::protobuf::EnumDescriptor* StatusResponse_Status_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_ota_5fservice_2eproto);
  return file_level_enum_descriptors_ota_5fservice_2eproto[0];
}
PROTOBUF_CONSTINIT const uint32_t StatusResponse_Status_internal_data_[] = {
    524288u, 0u, };
bool StatusResponse_Status_IsValid(int value) {
  return 0 <= value && value <= 7;
}
#if (__cplusplus < 201703) && \
  (!defined(_MSC_VER) || (_MSC_VER >= 1900 && _MSC_VER < 1912))

constexpr StatusResponse_Status StatusResponse::UNKNOWN;
constexpr StatusResponse_Status StatusResponse::DOWNLOADING;
constexpr StatusResponse_Status StatusResponse::VERIFYING;
constexpr StatusResponse_Status StatusResponse::INSTALLING;
constexpr StatusResponse_Status StatusResponse::REBOOTING;
constexpr StatusResponse_Status StatusResponse::COMPLETED;
constexpr StatusResponse_Status StatusResponse::FAILED;
constexpr StatusResponse_Status StatusResponse::ROLLED_BACK;
constexpr StatusResponse_Status StatusResponse::Status_MIN;
constexpr StatusResponse_Status StatusResponse::Status_MAX;
constexpr int StatusResponse::Status_ARRAYSIZE;

#endif  // (__cplusplus < 201703) &&
        // (!defined(_MSC_VER) || (_MSC_VER >= 1900 && _MSC_VER < 1912))
// ===================================================================

class CheckUpdateRequest::_Internal {
 public:
};

CheckUpdateRequest::CheckUpdateRequest(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:ota.CheckUpdateRequest)
}
inline PROTOBUF_NDEBUG_INLINE CheckUpdateRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from)
      : current_version_(arena, from.current_version_),
        hardware_type_(arena, from.hardware_type_),
        _cached_size_{0} {}

CheckUpdateRequest::CheckUpdateRequest(
    ::google::protobuf::Arena* arena,
    const CheckUpdateRequest& from)
    : ::google::protobuf::Message(arena) {
  CheckUpdateRequest* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_);
  _impl_.device_id_ = from._impl_.device_id_;

  // @@protoc_insertion_point(copy_constructor:ota.CheckUpdateRequest)
}
inline PROTOBUF_NDEBUG_INLINE CheckUpdateRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : current_version_(arena),
        hardware_type_(arena),
        _cached_size_{0} {}

inline void CheckUpdateRequest::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.device_id_ = {};
}
CheckUpdateRequest::~CheckUpdateRequest() {
  // @@protoc_insertion_point(destructor:ota.CheckUpdateRequest)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void CheckUpdateRequest::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.current_version_.Destroy();
  _impl_.hardware_type_.Destroy();
  _impl_.~Impl_();
}

PROTOBUF_NOINLINE void CheckUpdateRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:ota.CheckUpdateRequest)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.current_version_.ClearToEmpty();
  _impl_.hardware_type_.ClearToEmpty();
  _impl_.device_id_ = 0;
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* CheckUpdateRequest::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 3, 0, 59, 2> CheckUpdateRequest::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    3, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967288,  // skipmap
    offsetof(decltype(_table_), field_entries),
    3,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_CheckUpdateRequest_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // int32 device_id = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(CheckUpdateRequest, _impl_.device_id_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(CheckUpdateRequest, _impl_.device_id_)}},
    // string current_version = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(CheckUpdateRequest, _impl_.current_version_)}},
    // string hardware_type = 3;
    {::_pbi::TcParser::FastUS1,
     {26, 63, 0, PROTOBUF_FIELD_OFFSET(CheckUpdateRequest, _impl_.hardware_type_)}},
  }}, {{
    65535, 65535
  }}, {{
    // int32 device_id = 1;
    {PROTOBUF_FIELD_OFFSET(CheckUpdateRequest, _impl_.device_id_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
    // string current_version = 2;
    {PROTOBUF_FIELD_OFFSET(CheckUpdateRequest, _impl_.current_version_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string hardware_type = 3;
    {PROTOBUF_FIELD_OFFSET(CheckUpdateRequest, _impl_.hardware_type_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\26\0\17\15\0\0\0\0"
    "ota.CheckUpdateRequest"
    "current_version"
    "hardware_type"
  }},
};

::uint8_t* CheckUpdateRequest::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:ota.CheckUpdateRequest)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // int32 device_id = 1;
  if (this->_internal_device_id() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::
        WriteInt32ToArrayWithField<1>(
            stream, this->_internal_device_id(), target);
  }

  // string current_version = 2;
  if (!this->_internal_current_version().empty()) {
    const std::string& _s = this->_internal_current_version();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "ota.CheckUpdateRequest.current_version");
    target = stream->WriteStringMaybeAliased(2, _s, target);
  }

  // string hardware_type = 3;
  if (!this->_internal_hardware_type().empty()) {
    const std::string& _s = this->_internal_hardware_type();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "ota.CheckUpdateRequest.hardware_type");
    target = stream->WriteStringMaybeAliased(3, _s, target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:ota.CheckUpdateRequest)
  return target;
}

::size_t CheckUpdateRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:ota.CheckUpdateRequest)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string current_version = 2;
  if (!this->_internal_current_version().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_current_version());
  }

  // string hardware_type = 3;
  if (!this->_internal_hardware_type().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_hardware_type());
  }

  // int32 device_id = 1;
  if (this->_internal_device_id() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
        this->_internal_device_id());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData CheckUpdateRequest::_class_data_ = {
    CheckUpdateRequest::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* CheckUpdateRequest::GetClassData() const {
  return &_class_data_;
}

void CheckUpdateRequest::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<CheckUpdateRequest*>(&to_msg);
  auto& from = static_cast<const CheckUpdateRequest&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:ota.CheckUpdateRequest)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_current_version().empty()) {
    _this->_internal_set_current_version(from._internal_current_version());
  }
  if (!from._internal_hardware_type().empty()) {
    _this->_internal_set_hardware_type(from._internal_hardware_type());
  }
  if (from._internal_device_id() != 0) {
    _this->_internal_set_device_id(from._internal_device_id());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void CheckUpdateRequest::CopyFrom(const CheckUpdateRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:ota.CheckUpdateRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool CheckUpdateRequest::IsInitialized() const {
  return true;
}

::_pbi::CachedSize* CheckUpdateRequest::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void CheckUpdateRequest::InternalSwap(CheckUpdateRequest* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.current_version_, &other->_impl_.current_version_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.hardware_type_, &other->_impl_.hardware_type_, arena);
        swap(_impl_.device_id_, other->_impl_.device_id_);
}

::google::protobuf::Metadata CheckUpdateRequest::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_ota_5fservice_2eproto_getter, &descriptor_table_ota_5fservice_2eproto_once,
      file_level_metadata_ota_5fservice_2eproto[0]);
}
// ===================================================================

class CheckUpdateResponse::_Internal {
 public:
};

CheckUpdateResponse::CheckUpdateResponse(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:ota.CheckUpdateResponse)
}
inline PROTOBUF_NDEBUG_INLINE CheckUpdateResponse::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from)
      : new_version_(arena, from.new_version_),
        update_id_(arena, from.update_id_),
        changelog_(arena, from.changelog_),
        _cached_size_{0} {}

CheckUpdateResponse::CheckUpdateResponse(
    ::google::protobuf::Arena* arena,
    const CheckUpdateResponse& from)
    : ::google::protobuf::Message(arena) {
  CheckUpdateResponse* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_);
  ::memcpy(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, update_size_),
           reinterpret_cast<const char *>(&from._impl_) +
               offsetof(Impl_, update_size_),
           offsetof(Impl_, update_available_) -
               offsetof(Impl_, update_size_) +
               sizeof(Impl_::update_available_));

  // @@protoc_insertion_point(copy_constructor:ota.CheckUpdateResponse)
}
inline PROTOBUF_NDEBUG_INLINE CheckUpdateResponse::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : new_version_(arena),
        update_id_(arena),
        changelog_(arena),
        _cached_size_{0} {}

inline void CheckUpdateResponse::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, update_size_),
           0,
           offsetof(Impl_, update_available_) -
               offsetof(Impl_, update_size_) +
               sizeof(Impl_::update_available_));
}
CheckUpdateResponse::~CheckUpdateResponse() {
  // @@protoc_insertion_point(destructor:ota.CheckUpdateResponse)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void CheckUpdateResponse::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.new_version_.Destroy();
  _impl_.update_id_.Destroy();
  _impl_.changelog_.Destroy();
  _impl_.~Impl_();
}

PROTOBUF_NOINLINE void CheckUpdateResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:ota.CheckUpdateResponse)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.new_version_.ClearToEmpty();
  _impl_.update_id_.ClearToEmpty();
  _impl_.changelog_.ClearToEmpty();
  ::memset(&_impl_.update_size_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.update_available_) -
      reinterpret_cast<char*>(&_impl_.update_size_)) + sizeof(_impl_.update_available_));
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* CheckUpdateResponse::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<3, 5, 0, 61, 2> CheckUpdateResponse::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    5, 56,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967264,  // skipmap
    offsetof(decltype(_table_), field_entries),
    5,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_CheckUpdateResponse_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // bool update_available = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(CheckUpdateResponse, _impl_.update_available_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(CheckUpdateResponse, _impl_.update_available_)}},
    // string new_version = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(CheckUpdateResponse, _impl_.new_version_)}},
    // int64 update_size = 3;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(CheckUpdateResponse, _impl_.update_size_), 63>(),
     {24, 63, 0, PROTOBUF_FIELD_OFFSET(CheckUpdateResponse, _impl_.update_size_)}},
    // string update_id = 4;
    {::_pbi::TcParser::FastUS1,
     {34, 63, 0, PROTOBUF_FIELD_OFFSET(CheckUpdateResponse, _impl_.update_id_)}},
    // string changelog = 5;
    {::_pbi::TcParser::FastUS1,
     {42, 63, 0, PROTOBUF_FIELD_OFFSET(CheckUpdateResponse, _impl_.changelog_)}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }}, {{
    // bool update_available = 1;
    {PROTOBUF_FIELD_OFFSET(CheckUpdateResponse, _impl_.update_available_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kBool)},
    // string new_version = 2;
    {PROTOBUF_FIELD_OFFSET(CheckUpdateResponse, _impl_.new_version_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // int64 update_size = 3;
    {PROTOBUF_FIELD_OFFSET(CheckUpdateResponse, _impl_.update_size_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt64)},
    // string update_id = 4;
    {PROTOBUF_FIELD_OFFSET(CheckUpdateResponse, _impl_.update_id_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string changelog = 5;
    {PROTOBUF_FIELD_OFFSET(CheckUpdateResponse, _impl_.changelog_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\27\0\13\0\11\11\0\0"
    "ota.CheckUpdateResponse"
    "new_version"
    "update_id"
    "changelog"
  }},
};

::uint8_t* CheckUpdateResponse::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:ota.CheckUpdateResponse)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // bool update_available = 1;
  if (this->_internal_update_available() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(
        1, this->_internal_update_available(), target);
  }

  // string new_version = 2;
  if (!this->_internal_new_version().empty()) {
    const std::string& _s = this->_internal_new_version();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "ota.CheckUpdateResponse.new_version");
    target = stream->WriteStringMaybeAliased(2, _s, target);
  }

  // int64 update_size = 3;
  if (this->_internal_update_size() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::
        WriteInt64ToArrayWithField<3>(
            stream, this->_internal_update_size(), target);
  }

  // string update_id = 4;
  if (!this->_internal_update_id().empty()) {
    const std::string& _s = this->_internal_update_id();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "ota.CheckUpdateResponse.update_id");
    target = stream->WriteStringMaybeAliased(4, _s, target);
  }

  // string changelog = 5;
  if (!this->_internal_changelog().empty()) {
    const std::string& _s = this->_internal_changelog();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "ota.CheckUpdateResponse.changelog");
    target = stream->WriteStringMaybeAliased(5, _s, target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:ota.CheckUpdateResponse)
  return target;
}

::size_t CheckUpdateResponse::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:ota.CheckUpdateResponse)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string new_version = 2;
  if (!this->_internal_new_version().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_new_version());
  }

  // string update_id = 4;
  if (!this->_internal_update_id().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_update_id());
  }

  // string changelog = 5;
  if (!this->_internal_changelog().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_changelog());
  }

  // int64 update_size = 3;
  if (this->_internal_update_size() != 0) {
    total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(
        this->_internal_update_size());
  }

  // bool update_available = 1;
  if (this->_internal_update_available() != 0) {
    total_size += 2;
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData CheckUpdateResponse::_class_data_ = {
    CheckUpdateResponse::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* CheckUpdateResponse::GetClassData() const {
  return &_class_data_;
}

void CheckUpdateResponse::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<CheckUpdateResponse*>(&to_msg);
  auto& from = static_cast<const CheckUpdateResponse&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:ota.CheckUpdateResponse)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_new_version().empty()) {
    _this->_internal_set_new_version(from._internal_new_version());
  }
  if (!from._internal_update_id().empty()) {
    _this->_internal_set_update_id(from._internal_update_id());
  }
  if (!from._internal_changelog().empty()) {
    _this->_internal_set_changelog(from._internal_changelog());
  }
  if (from._internal_update_size() != 0) {
    _this->_internal_set_update_size(from._internal_update_size());
  }
  if (from._internal_update_available() != 0) {
    _this->_internal_set_update_available(from._internal_update_available());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void CheckUpdateResponse::CopyFrom(const CheckUpdateResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:ota.CheckUpdateResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool CheckUpdateResponse::IsInitialized() const {
  return true;
}

::_pbi::CachedSize* CheckUpdateResponse::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void CheckUpdateResponse::InternalSwap(CheckUpdateResponse* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.new_version_, &other->_impl_.new_version_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.update_id_, &other->_impl_.update_id_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.changelog_, &other->_impl_.changelog_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(CheckUpdateResponse, _impl_.update_available_)
      + sizeof(CheckUpdateResponse::_impl_.update_available_)
      - PROTOBUF_FIELD_OFFSET(CheckUpdateResponse, _impl_.update_size_)>(
          reinterpret_cast<char*>(&_impl_.update_size_),
          reinterpret_cast<char*>(&other->_impl_.update_size_));
}

::google::protobuf::Metadata CheckUpdateResponse::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_ota_5fservice_2eproto_getter, &descriptor_table_ota_5fservice_2eproto_once,
      file_level_metadata_ota_5fservice_2eproto[1]);
}
// ===================================================================

class DownloadRequest::_Internal {
 public:
};

DownloadRequest::DownloadRequest(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:ota.DownloadRequest)
}
inline PROTOBUF_NDEBUG_INLINE DownloadRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from)
      : update_id_(arena, from.update_id_),
        jwt_token_(arena, from.jwt_token_),
        _cached_size_{0} {}

DownloadRequest::DownloadRequest(
    ::google::protobuf::Arena* arena,
    const DownloadRequest& from)
    : ::google::protobuf::Message(arena) {
  DownloadRequest* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_);
  _impl_.device_id_ = from._impl_.device_id_;

  // @@protoc_insertion_point(copy_constructor:ota.DownloadRequest)
}
inline PROTOBUF_NDEBUG_INLINE DownloadRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : update_id_(arena),
        jwt_token_(arena),
        _cached_size_{0} {}

inline void DownloadRequest::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.device_id_ = {};
}
DownloadRequest::~DownloadRequest() {
  // @@protoc_insertion_point(destructor:ota.DownloadRequest)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void DownloadRequest::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.update_id_.Destroy();
  _impl_.jwt_token_.Destroy();
  _impl_.~Impl_();
}

PROTOBUF_NOINLINE void DownloadRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:ota.DownloadRequest)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.update_id_.ClearToEmpty();
  _impl_.jwt_token_.ClearToEmpty();
  _impl_.device_id_ = 0;
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* DownloadRequest::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 3, 0, 46, 2> DownloadRequest::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    3, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967288,  // skipmap
    offsetof(decltype(_table_), field_entries),
    3,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_DownloadRequest_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // int32 device_id = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(DownloadRequest, _impl_.device_id_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(DownloadRequest, _impl_.device_id_)}},
    // string update_id = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(DownloadRequest, _impl_.update_id_)}},
    // string jwt_token = 3;
    {::_pbi::TcParser::FastUS1,
     {26, 63, 0, PROTOBUF_FIELD_OFFSET(DownloadRequest, _impl_.jwt_token_)}},
  }}, {{
    65535, 65535
  }}, {{
    // int32 device_id = 1;
    {PROTOBUF_FIELD_OFFSET(DownloadRequest, _impl_.device_id_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
    // string update_id = 2;
    {PROTOBUF_FIELD_OFFSET(DownloadRequest, _impl_.update_id_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string jwt_token = 3;
    {PROTOBUF_FIELD_OFFSET(DownloadRequest, _impl_.jwt_token_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\23\0\11\11\0\0\0\0"
    "ota.DownloadRequest"
    "update_id"
    "jwt_token"
  }},
};

::uint8_t* DownloadRequest::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:ota.DownloadRequest)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // int32 device_id = 1;
  if (this->_internal_device_id() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::
        WriteInt32ToArrayWithField<1>(
            stream, this->_internal_device_id(), target);
  }

  // string update_id = 2;
  if (!this->_internal_update_id().empty()) {
    const std::string& _s = this->_internal_update_id();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "ota.DownloadRequest.update_id");
    target = stream->WriteStringMaybeAliased(2, _s, target);
  }

  // string jwt_token = 3;
  if (!this->_internal_jwt_token().empty()) {
    const std::string& _s = this->_internal_jwt_token();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "ota.DownloadRequest.jwt_token");
    target = stream->WriteStringMaybeAliased(3, _s, target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:ota.DownloadRequest)
  return target;
}

::size_t DownloadRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:ota.DownloadRequest)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string update_id = 2;
  if (!this->_internal_update_id().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_update_id());
  }

  // string jwt_token = 3;
  if (!this->_internal_jwt_token().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_jwt_token());
  }

  // int32 device_id = 1;
  if (this->_internal_device_id() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
        this->_internal_device_id());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData DownloadRequest::_class_data_ = {
    DownloadRequest::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* DownloadRequest::GetClassData() const {
  return &_class_data_;
}

void DownloadRequest::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<DownloadRequest*>(&to_msg);
  auto& from = static_cast<const DownloadRequest&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:ota.DownloadRequest)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_update_id().empty()) {
    _this->_internal_set_update_id(from._internal_update_id());
  }
  if (!from._internal_jwt_token().empty()) {
    _this->_internal_set_jwt_token(from._internal_jwt_token());
  }
  if (from._internal_device_id() != 0) {
    _this->_internal_set_device_id(from._internal_device_id());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void DownloadRequest::CopyFrom(const DownloadRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:ota.DownloadRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool DownloadRequest::IsInitialized() const {
  return true;
}

::_pbi::CachedSize* DownloadRequest::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void DownloadRequest::InternalSwap(DownloadRequest* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.update_id_, &other->_impl_.update_id_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.jwt_token_, &other->_impl_.jwt_token_, arena);
        swap(_impl_.device_id_, other->_impl_.device_id_);
}

::google::protobuf::Metadata DownloadRequest::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_ota_5fservice_2eproto_getter, &descriptor_table_ota_5fservice_2eproto_once,
      file_level_metadata_ota_5fservice_2eproto[2]);
}
// ===================================================================

class DownloadChunk::_Internal {
 public:
};

DownloadChunk::DownloadChunk(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:ota.DownloadChunk)
}
inline PROTOBUF_NDEBUG_INLINE DownloadChunk::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from)
      : data_(arena, from.data_),
        _cached_size_{0} {}

DownloadChunk::DownloadChunk(
    ::google::protobuf::Arena* arena,
    const DownloadChunk& from)
    : ::google::protobuf::Message(arena) {
  DownloadChunk* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_);
  ::memcpy(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, chunk_id_),
           reinterpret_cast<const char *>(&from._impl_) +
               offsetof(Impl_, chunk_id_),
           offsetof(Impl_, last_chunk_) -
               offsetof(Impl_, chunk_id_) +
               sizeof(Impl_::last_chunk_));

  // @@protoc_insertion_point(copy_constructor:ota.DownloadChunk)
}
inline PROTOBUF_NDEBUG_INLINE DownloadChunk::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : data_(arena),
        _cached_size_{0} {}

inline void DownloadChunk::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, chunk_id_),
           0,
           offsetof(Impl_, last_chunk_) -
               offsetof(Impl_, chunk_id_) +
               sizeof(Impl_::last_chunk_));
}
DownloadChunk::~DownloadChunk() {
  // @@protoc_insertion_point(destructor:ota.DownloadChunk)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void DownloadChunk::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.data_.Destroy();
  _impl_.~Impl_();
}

PROTOBUF_NOINLINE void DownloadChunk::Clear() {
// @@protoc_insertion_point(message_clear_start:ota.DownloadChunk)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.data_.ClearToEmpty();
  ::memset(&_impl_.chunk_id_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.last_chunk_) -
      reinterpret_cast<char*>(&_impl_.chunk_id_)) + sizeof(_impl_.last_chunk_));
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* DownloadChunk::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 3, 0, 0, 2> DownloadChunk::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    3, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967288,  // skipmap
    offsetof(decltype(_table_), field_entries),
    3,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_DownloadChunk_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // bytes data = 1;
    {::_pbi::TcParser::FastBS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(DownloadChunk, _impl_.data_)}},
    // int32 chunk_id = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(DownloadChunk, _impl_.chunk_id_), 63>(),
     {16, 63, 0, PROTOBUF_FIELD_OFFSET(DownloadChunk, _impl_.chunk_id_)}},
    // bool last_chunk = 3;
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(DownloadChunk, _impl_.last_chunk_), 63>(),
     {24, 63, 0, PROTOBUF_FIELD_OFFSET(DownloadChunk, _impl_.last_chunk_)}},
  }}, {{
    65535, 65535
  }}, {{
    // bytes data = 1;
    {PROTOBUF_FIELD_OFFSET(DownloadChunk, _impl_.data_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kBytes | ::_fl::kRepAString)},
    // int32 chunk_id = 2;
    {PROTOBUF_FIELD_OFFSET(DownloadChunk, _impl_.chunk_id_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
    // bool last_chunk = 3;
    {PROTOBUF_FIELD_OFFSET(DownloadChunk, _impl_.last_chunk_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kBool)},
  }},
  // no aux_entries
  {{
  }},
};

::uint8_t* DownloadChunk::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:ota.DownloadChunk)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // bytes data = 1;
  if (!this->_internal_data().empty()) {
    const std::string& _s = this->_internal_data();
    target = stream->WriteBytesMaybeAliased(1, _s, target);
  }

  // int32 chunk_id = 2;
  if (this->_internal_chunk_id() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::
        WriteInt32ToArrayWithField<2>(
            stream, this->_internal_chunk_id(), target);
  }

  // bool last_chunk = 3;
  if (this->_internal_last_chunk() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(
        3, this->_internal_last_chunk(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:ota.DownloadChunk)
  return target;
}

::size_t DownloadChunk::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:ota.DownloadChunk)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // bytes data = 1;
  if (!this->_internal_data().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::BytesSize(
                                    this->_internal_data());
  }

  // int32 chunk_id = 2;
  if (this->_internal_chunk_id() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
        this->_internal_chunk_id());
  }

  // bool last_chunk = 3;
  if (this->_internal_last_chunk() != 0) {
    total_size += 2;
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData DownloadChunk::_class_data_ = {
    DownloadChunk::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* DownloadChunk::GetClassData() const {
  return &_class_data_;
}

void DownloadChunk::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<DownloadChunk*>(&to_msg);
  auto& from = static_cast<const DownloadChunk&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:ota.DownloadChunk)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_data().empty()) {
    _this->_internal_set_data(from._internal_data());
  }
  if (from._internal_chunk_id() != 0) {
    _this->_internal_set_chunk_id(from._internal_chunk_id());
  }
  if (from._internal_last_chunk() != 0) {
    _this->_internal_set_last_chunk(from._internal_last_chunk());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void DownloadChunk::CopyFrom(const DownloadChunk& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:ota.DownloadChunk)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool DownloadChunk::IsInitialized() const {
  return true;
}

::_pbi::CachedSize* DownloadChunk::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void DownloadChunk::InternalSwap(DownloadChunk* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.data_, &other->_impl_.data_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(DownloadChunk, _impl_.last_chunk_)
      + sizeof(DownloadChunk::_impl_.last_chunk_)
      - PROTOBUF_FIELD_OFFSET(DownloadChunk, _impl_.chunk_id_)>(
          reinterpret_cast<char*>(&_impl_.chunk_id_),
          reinterpret_cast<char*>(&other->_impl_.chunk_id_));
}

::google::protobuf::Metadata DownloadChunk::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_ota_5fservice_2eproto_getter, &descriptor_table_ota_5fservice_2eproto_once,
      file_level_metadata_ota_5fservice_2eproto[3]);
}
// ===================================================================

class InstallRequest::_Internal {
 public:
};

InstallRequest::InstallRequest(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:ota.InstallRequest)
}
inline PROTOBUF_NDEBUG_INLINE InstallRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from)
      : update_id_(arena, from.update_id_),
        _cached_size_{0} {}

InstallRequest::InstallRequest(
    ::google::protobuf::Arena* arena,
    const InstallRequest& from)
    : ::google::protobuf::Message(arena) {
  InstallRequest* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_);
  ::memcpy(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, device_id_),
           reinterpret_cast<const char *>(&from._impl_) +
               offsetof(Impl_, device_id_),
           offsetof(Impl_, allow_rollback_) -
               offsetof(Impl_, device_id_) +
               sizeof(Impl_::allow_rollback_));

  // @@protoc_insertion_point(copy_constructor:ota.InstallRequest)
}
inline PROTOBUF_NDEBUG_INLINE InstallRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : update_id_(arena),
        _cached_size_{0} {}

inline void InstallRequest::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, device_id_),
           0,
           offsetof(Impl_, allow_rollback_) -
               offsetof(Impl_, device_id_) +
               sizeof(Impl_::allow_rollback_));
}
InstallRequest::~InstallRequest() {
  // @@protoc_insertion_point(destructor:ota.InstallRequest)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void InstallRequest::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.update_id_.Destroy();
  _impl_.~Impl_();
}

PROTOBUF_NOINLINE void InstallRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:ota.InstallRequest)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.update_id_.ClearToEmpty();
  ::memset(&_impl_.device_id_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.allow_rollback_) -
      reinterpret_cast<char*>(&_impl_.device_id_)) + sizeof(_impl_.allow_rollback_));
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* InstallRequest::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 3, 0, 36, 2> InstallRequest::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    3, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967288,  // skipmap
    offsetof(decltype(_table_), field_entries),
    3,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_InstallRequest_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // int32 device_id = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(InstallRequest, _impl_.device_id_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(InstallRequest, _impl_.device_id_)}},
    // string update_id = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(InstallRequest, _impl_.update_id_)}},
    // bool allow_rollback = 3;
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(InstallRequest, _impl_.allow_rollback_), 63>(),
     {24, 63, 0, PROTOBUF_FIELD_OFFSET(InstallRequest, _impl_.allow_rollback_)}},
  }}, {{
    65535, 65535
  }}, {{
    // int32 device_id = 1;
    {PROTOBUF_FIELD_OFFSET(InstallRequest, _impl_.device_id_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
    // string update_id = 2;
    {PROTOBUF_FIELD_OFFSET(InstallRequest, _impl_.update_id_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // bool allow_rollback = 3;
    {PROTOBUF_FIELD_OFFSET(InstallRequest, _impl_.allow_rollback_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kBool)},
  }},
  // no aux_entries
  {{
    "\22\0\11\0\0\0\0\0"
    "ota.InstallRequest"
    "update_id"
  }},
};

::uint8_t* InstallRequest::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:ota.InstallRequest)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // int32 device_id = 1;
  if (this->_internal_device_id() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::
        WriteInt32ToArrayWithField<1>(
            stream, this->_internal_device_id(), target);
  }

  // string update_id = 2;
  if (!this->_internal_update_id().empty()) {
    const std::string& _s = this->_internal_update_id();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "ota.InstallRequest.update_id");
    target = stream->WriteStringMaybeAliased(2, _s, target);
  }

  // bool allow_rollback = 3;
  if (this->_internal_allow_rollback() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(
        3, this->_internal_allow_rollback(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:ota.InstallRequest)
  return target;
}

::size_t InstallRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:ota.InstallRequest)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string update_id = 2;
  if (!this->_internal_update_id().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_update_id());
  }

  // int32 device_id = 1;
  if (this->_internal_device_id() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
        this->_internal_device_id());
  }

  // bool allow_rollback = 3;
  if (this->_internal_allow_rollback() != 0) {
    total_size += 2;
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData InstallRequest::_class_data_ = {
    InstallRequest::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* InstallRequest::GetClassData() const {
  return &_class_data_;
}

void InstallRequest::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<InstallRequest*>(&to_msg);
  auto& from = static_cast<const InstallRequest&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:ota.InstallRequest)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_update_id().empty()) {
    _this->_internal_set_update_id(from._internal_update_id());
  }
  if (from._internal_device_id() != 0) {
    _this->_internal_set_device_id(from._internal_device_id());
  }
  if (from._internal_allow_rollback() != 0) {
    _this->_internal_set_allow_rollback(from._internal_allow_rollback());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void InstallRequest::CopyFrom(const InstallRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:ota.InstallRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool InstallRequest::IsInitialized() const {
  return true;
}

::_pbi::CachedSize* InstallRequest::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void InstallRequest::InternalSwap(InstallRequest* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.update_id_, &other->_impl_.update_id_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(InstallRequest, _impl_.allow_rollback_)
      + sizeof(InstallRequest::_impl_.allow_rollback_)
      - PROTOBUF_FIELD_OFFSET(InstallRequest, _impl_.device_id_)>(
          reinterpret_cast<char*>(&_impl_.device_id_),
          reinterpret_cast<char*>(&other->_impl_.device_id_));
}

::google::protobuf::Metadata InstallRequest::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_ota_5fservice_2eproto_getter, &descriptor_table_ota_5fservice_2eproto_once,
      file_level_metadata_ota_5fservice_2eproto[4]);
}
// ===================================================================

class InstallResponse::_Internal {
 public:
};

InstallResponse::InstallResponse(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:ota.InstallResponse)
}
inline PROTOBUF_NDEBUG_INLINE InstallResponse::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from)
      : message_(arena, from.message_),
        installation_id_(arena, from.installation_id_),
        _cached_size_{0} {}

InstallResponse::InstallResponse(
    ::google::protobuf::Arena* arena,
    const InstallResponse& from)
    : ::google::protobuf::Message(arena) {
  InstallResponse* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_);
  _impl_.success_ = from._impl_.success_;

  // @@protoc_insertion_point(copy_constructor:ota.InstallResponse)
}
inline PROTOBUF_NDEBUG_INLINE InstallResponse::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : message_(arena),
        installation_id_(arena),
        _cached_size_{0} {}

inline void InstallResponse::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.success_ = {};
}
InstallResponse::~InstallResponse() {
  // @@protoc_insertion_point(destructor:ota.InstallResponse)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void InstallResponse::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.message_.Destroy();
  _impl_.installation_id_.Destroy();
  _impl_.~Impl_();
}

PROTOBUF_NOINLINE void InstallResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:ota.InstallResponse)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.message_.ClearToEmpty();
  _impl_.installation_id_.ClearToEmpty();
  _impl_.success_ = false;
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* InstallResponse::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 3, 0, 50, 2> InstallResponse::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    3, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967288,  // skipmap
    offsetof(decltype(_table_), field_entries),
    3,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_InstallResponse_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // bool success = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(InstallResponse, _impl_.success_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(InstallResponse, _impl_.success_)}},
    // string message = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(InstallResponse, _impl_.message_)}},
    // string installation_id = 3;
    {::_pbi::TcParser::FastUS1,
     {26, 63, 0, PROTOBUF_FIELD_OFFSET(InstallResponse, _impl_.installation_id_)}},
  }}, {{
    65535, 65535
  }}, {{
    // bool success = 1;
    {PROTOBUF_FIELD_OFFSET(InstallResponse, _impl_.success_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kBool)},
    // string message = 2;
    {PROTOBUF_FIELD_OFFSET(InstallResponse, _impl_.message_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string installation_id = 3;
    {PROTOBUF_FIELD_OFFSET(InstallResponse, _impl_.installation_id_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\23\0\7\17\0\0\0\0"
    "ota.InstallResponse"
    "message"
    "installation_id"
  }},
};

::uint8_t* InstallResponse::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:ota.InstallResponse)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // bool success = 1;
  if (this->_internal_success() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(
        1, this->_internal_success(), target);
  }

  // string message = 2;
  if (!this->_internal_message().empty()) {
    const std::string& _s = this->_internal_message();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "ota.InstallResponse.message");
    target = stream->WriteStringMaybeAliased(2, _s, target);
  }

  // string installation_id = 3;
  if (!this->_internal_installation_id().empty()) {
    const std::string& _s = this->_internal_installation_id();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "ota.InstallResponse.installation_id");
    target = stream->WriteStringMaybeAliased(3, _s, target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:ota.InstallResponse)
  return target;
}

::size_t InstallResponse::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:ota.InstallResponse)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string message = 2;
  if (!this->_internal_message().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_message());
  }

  // string installation_id = 3;
  if (!this->_internal_installation_id().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_installation_id());
  }

  // bool success = 1;
  if (this->_internal_success() != 0) {
    total_size += 2;
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData InstallResponse::_class_data_ = {
    InstallResponse::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* InstallResponse::GetClassData() const {
  return &_class_data_;
}

void InstallResponse::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<InstallResponse*>(&to_msg);
  auto& from = static_cast<const InstallResponse&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:ota.InstallResponse)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_message().empty()) {
    _this->_internal_set_message(from._internal_message());
  }
  if (!from._internal_installation_id().empty()) {
    _this->_internal_set_installation_id(from._internal_installation_id());
  }
  if (from._internal_success() != 0) {
    _this->_internal_set_success(from._internal_success());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void InstallResponse::CopyFrom(const InstallResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:ota.InstallResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool InstallResponse::IsInitialized() const {
  return true;
}

::_pbi::CachedSize* InstallResponse::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void InstallResponse::InternalSwap(InstallResponse* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.message_, &other->_impl_.message_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.installation_id_, &other->_impl_.installation_id_, arena);
        swap(_impl_.success_, other->_impl_.success_);
}

::google::protobuf::Metadata InstallResponse::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_ota_5fservice_2eproto_getter, &descriptor_table_ota_5fservice_2eproto_once,
      file_level_metadata_ota_5fservice_2eproto[5]);
}
// ===================================================================

class StatusRequest::_Internal {
 public:
};

StatusRequest::StatusRequest(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:ota.StatusRequest)
}
inline PROTOBUF_NDEBUG_INLINE StatusRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from)
      : installation_id_(arena, from.installation_id_),
        _cached_size_{0} {}

StatusRequest::StatusRequest(
    ::google::protobuf::Arena* arena,
    const StatusRequest& from)
    : ::google::protobuf::Message(arena) {
  StatusRequest* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_);
  _impl_.device_id_ = from._impl_.device_id_;

  // @@protoc_insertion_point(copy_constructor:ota.StatusRequest)
}
inline PROTOBUF_NDEBUG_INLINE StatusRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : installation_id_(arena),
        _cached_size_{0} {}

inline void StatusRequest::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.device_id_ = {};
}
StatusRequest::~StatusRequest() {
  // @@protoc_insertion_point(destructor:ota.StatusRequest)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void StatusRequest::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.installation_id_.Destroy();
  _impl_.~Impl_();
}

PROTOBUF_NOINLINE void StatusRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:ota.StatusRequest)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.installation_id_.ClearToEmpty();
  _impl_.device_id_ = 0;
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* StatusRequest::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 41, 2> StatusRequest::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_StatusRequest_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    // string installation_id = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(StatusRequest, _impl_.installation_id_)}},
    // int32 device_id = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(StatusRequest, _impl_.device_id_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(StatusRequest, _impl_.device_id_)}},
  }}, {{
    65535, 65535
  }}, {{
    // int32 device_id = 1;
    {PROTOBUF_FIELD_OFFSET(StatusRequest, _impl_.device_id_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
    // string installation_id = 2;
    {PROTOBUF_FIELD_OFFSET(StatusRequest, _impl_.installation_id_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\21\0\17\0\0\0\0\0"
    "ota.StatusRequest"
    "installation_id"
  }},
};

::uint8_t* StatusRequest::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:ota.StatusRequest)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // int32 device_id = 1;
  if (this->_internal_device_id() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::
        WriteInt32ToArrayWithField<1>(
            stream, this->_internal_device_id(), target);
  }

  // string installation_id = 2;
  if (!this->_internal_installation_id().empty()) {
    const std::string& _s = this->_internal_installation_id();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "ota.StatusRequest.installation_id");
    target = stream->WriteStringMaybeAliased(2, _s, target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:ota.StatusRequest)
  return target;
}

::size_t StatusRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:ota.StatusRequest)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string installation_id = 2;
  if (!this->_internal_installation_id().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_installation_id());
  }

  // int32 device_id = 1;
  if (this->_internal_device_id() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
        this->_internal_device_id());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData StatusRequest::_class_data_ = {
    StatusRequest::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* StatusRequest::GetClassData() const {
  return &_class_data_;
}

void StatusRequest::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<StatusRequest*>(&to_msg);
  auto& from = static_cast<const StatusRequest&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:ota.StatusRequest)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_installation_id().empty()) {
    _this->_internal_set_installation_id(from._internal_installation_id());
  }
  if (from._internal_device_id() != 0) {
    _this->_internal_set_device_id(from._internal_device_id());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void StatusRequest::CopyFrom(const StatusRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:ota.StatusRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool StatusRequest::IsInitialized() const {
  return true;
}

::_pbi::CachedSize* StatusRequest::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void StatusRequest::InternalSwap(StatusRequest* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.installation_id_, &other->_impl_.installation_id_, arena);
        swap(_impl_.device_id_, other->_impl_.device_id_);
}

::google::protobuf::Metadata StatusRequest::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_ota_5fservice_2eproto_getter, &descriptor_table_ota_5fservice_2eproto_once,
      file_level_metadata_ota_5fservice_2eproto[6]);
}
// ===================================================================

class StatusResponse::_Internal {
 public:
};

StatusResponse::StatusResponse(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:ota.StatusResponse)
}
inline PROTOBUF_NDEBUG_INLINE StatusResponse::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from)
      : message_(arena, from.message_),
        _cached_size_{0} {}

StatusResponse::StatusResponse(
    ::google::protobuf::Arena* arena,
    const StatusResponse& from)
    : ::google::protobuf::Message(arena) {
  StatusResponse* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_);
  ::memcpy(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, status_),
           reinterpret_cast<const char *>(&from._impl_) +
               offsetof(Impl_, status_),
           offsetof(Impl_, progress_) -
               offsetof(Impl_, status_) +
               sizeof(Impl_::progress_));

  // @@protoc_insertion_point(copy_constructor:ota.StatusResponse)
}
inline PROTOBUF_NDEBUG_INLINE StatusResponse::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : message_(arena),
        _cached_size_{0} {}

inline void StatusResponse::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, status_),
           0,
           offsetof(Impl_, progress_) -
               offsetof(Impl_, status_) +
               sizeof(Impl_::progress_));
}
StatusResponse::~StatusResponse() {
  // @@protoc_insertion_point(destructor:ota.StatusResponse)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void StatusResponse::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.message_.Destroy();
  _impl_.~Impl_();
}

PROTOBUF_NOINLINE void StatusResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:ota.StatusResponse)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.message_.ClearToEmpty();
  ::memset(&_impl_.status_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.progress_) -
      reinterpret_cast<char*>(&_impl_.status_)) + sizeof(_impl_.progress_));
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* StatusResponse::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 3, 0, 34, 2> StatusResponse::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    3, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967288,  // skipmap
    offsetof(decltype(_table_), field_entries),
    3,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_StatusResponse_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // .ota.StatusResponse.Status status = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(StatusResponse, _impl_.status_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(StatusResponse, _impl_.status_)}},
    // int32 progress = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(StatusResponse, _impl_.progress_), 63>(),
     {16, 63, 0, PROTOBUF_FIELD_OFFSET(StatusResponse, _impl_.progress_)}},
    // string message = 3;
    {::_pbi::TcParser::FastUS1,
     {26, 63, 0, PROTOBUF_FIELD_OFFSET(StatusResponse, _impl_.message_)}},
  }}, {{
    65535, 65535
  }}, {{
    // .ota.StatusResponse.Status status = 1;
    {PROTOBUF_FIELD_OFFSET(StatusResponse, _impl_.status_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kOpenEnum)},
    // int32 progress = 2;
    {PROTOBUF_FIELD_OFFSET(StatusResponse, _impl_.progress_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
    // string message = 3;
    {PROTOBUF_FIELD_OFFSET(StatusResponse, _impl_.message_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\22\0\0\7\0\0\0\0"
    "ota.StatusResponse"
    "message"
  }},
};

::uint8_t* StatusResponse::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:ota.StatusResponse)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // .ota.StatusResponse.Status status = 1;
  if (this->_internal_status() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
        1, this->_internal_status(), target);
  }

  // int32 progress = 2;
  if (this->_internal_progress() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::
        WriteInt32ToArrayWithField<2>(
            stream, this->_internal_progress(), target);
  }

  // string message = 3;
  if (!this->_internal_message().empty()) {
    const std::string& _s = this->_internal_message();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "ota.StatusResponse.message");
    target = stream->WriteStringMaybeAliased(3, _s, target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:ota.StatusResponse)
  return target;
}

::size_t StatusResponse::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:ota.StatusResponse)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string message = 3;
  if (!this->_internal_message().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_message());
  }

  // .ota.StatusResponse.Status status = 1;
  if (this->_internal_status() != 0) {
    total_size += 1 +
                  ::_pbi::WireFormatLite::EnumSize(this->_internal_status());
  }

  // int32 progress = 2;
  if (this->_internal_progress() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
        this->_internal_progress());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData StatusResponse::_class_data_ = {
    StatusResponse::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* StatusResponse::GetClassData() const {
  return &_class_data_;
}

void StatusResponse::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<StatusResponse*>(&to_msg);
  auto& from = static_cast<const StatusResponse&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:ota.StatusResponse)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_message().empty()) {
    _this->_internal_set_message(from._internal_message());
  }
  if (from._internal_status() != 0) {
    _this->_internal_set_status(from._internal_status());
  }
  if (from._internal_progress() != 0) {
    _this->_internal_set_progress(from._internal_progress());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void StatusResponse::CopyFrom(const StatusResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:ota.StatusResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool StatusResponse::IsInitialized() const {
  return true;
}

::_pbi::CachedSize* StatusResponse::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void StatusResponse::InternalSwap(StatusResponse* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.message_, &other->_impl_.message_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(StatusResponse, _impl_.progress_)
      + sizeof(StatusResponse::_impl_.progress_)
      - PROTOBUF_FIELD_OFFSET(StatusResponse, _impl_.status_)>(
          reinterpret_cast<char*>(&_impl_.status_),
          reinterpret_cast<char*>(&other->_impl_.status_));
}

::google::protobuf::Metadata StatusResponse::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_ota_5fservice_2eproto_getter, &descriptor_table_ota_5fservice_2eproto_once,
      file_level_metadata_ota_5fservice_2eproto[7]);
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace ota
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
#include "google/protobuf/port_undef.inc"
